from Core import pieces
from .Utilities import *

def init_pieces():
    piece_dict = {"w_rook_1", pieces.Piece('r', 'w', 'a1'),
                  "w_rook_2", pieces.Piece('r', 'w', 'h1'),
                  "w_knight_1", pieces.Piece('n', 'w', 'b1'),
                  "w_knight_2", pieces.Piece('n', 'w', 'g1'),
                  "w_bishop_1", pieces.Piece('b', 'w', 'c1'),
                  "w_bishop_2", pieces.Piece('b', 'w', 'f1'),
                  "w_pawn_1", pieces.Piece('p', 'w', 'a2'),
                  "w_pawn_2", pieces.Piece('p', 'w', 'b2'),
                  "w_pawn_3", pieces.Piece('p', 'w', 'c2'),
                  "w_pawn_4", pieces.Piece('p', 'w', 'd2'),
                  "w_pawn_5", pieces.Piece('p', 'w', 'e2'),
                  "w_pawn_6", pieces.Piece('p', 'w', 'f2'),
                  "w_pawn_7", pieces.Piece('p', 'w', 'g2'),
                  "w_pawn_8", pieces.Piece('p', 'w', 'h2'),
                  "w_king_1", pieces.Piece('k', 'w', 'e1'),
                  "w_queen_1", pieces.Piece('q', 'w', 'd1'),

                  "b_xrook_1", pieces.Piece('r', 'w', 'a8'),
                  "b_rook_2", pieces.Piece('r', 'w', 'h8'),
                  "b_knight_1", pieces.Piece('n', 'w', 'b8'),
                  "b_knight_2", pieces.Piece('n', 'w', 'g8'),
                  "b_bishop_1", pieces.Piece('b', 'w', 'c8'),
                  "b_bishop_2", pieces.Piece('b', 'w', 'f8'),
                  "b_pawn_1", pieces.Piece('p', 'w', 'a7'),
                  "b_pawn_2", pieces.Piece('p', 'w', 'b7'),
                  "b_pawn_3", pieces.Piece('p', 'w', 'c7'),
                  "b_pawn_4", pieces.Piece('p', 'w', 'd7'),
                  "b_pawn_5", pieces.Piece('p', 'w', 'e7'),
                  "b_pawn_6", pieces.Piece('p', 'w', 'f7'),
                  "b_pawn_7", pieces.Piece('p', 'w', 'g7'),
                  "b_pawn_8", pieces.Piece('p', 'w', 'h7'),
                  "b_king_1", pieces.Piece('k', 'w', 'e8'),
                  "b_queen_1", pieces.Piece('q', 'w', 'd8')}